spring:
  application:
    name: spring-cloud-config
  zipkin:
    base-url: http://localhost:9411
  boot:
    admin:
      client:
        url: http://localhost:8084
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/swing-itoken/itoken-config.git
          search-paths: config
          username: qiu-qian
          password: LQqhzn18845124018

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8501/eureka/