spring:
  application:
    name: itoken-eureka

  zipkin:
    base-url: http://localhost:9411

  boot:
    admin:
      client:
        url: http://localhost:8084

server:
  port: 8501

eureka:
  instance:
    hostname: 172.18.29.222
  client:
    # 表示是否将自己注册到Eureka ,因为要构建集群环境，需要将自己注册到集权，所以应该开启
    registerWithEureka: true
    # 表示是否从Eureka获取注册信息，如果是单一节点，不需要同步其他的Eureka节点，则可以设置为 false ，但此处为集群，应该设置为true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/